<div class="container-frete">
    <div class="title-frete">
        Digite o seu CEP:<br>
        <input id="cep" type="text"/>
        <input id="botao" type="button" value="<?php echo $this->__('Calcular'); ?>"/>
    </div>
    <div id="content-frete">
        
    </div>
<?php
$produto = Mage::registry('product');
/*echo "<pre>";
var_export($produto->debug());
echo "</pre>";*/
?>
<script>
      Event.observe('botao', 'click', function(event) {
          new Ajax.Updater('content-frete', '/Freteproduto?cep='+$('cep').getValue()+'&productid=<?php echo $produto->getId();?>', { method: 'get' });

      });
         
      
    </script>
</div>